

import { useState, useEffect } from 'react';

import "../../App.css";
import { useViewport } from "../../context/ViewportContext";
import { TableChart } from '../../components/TableChart';

export const CategoryBreakdownSlide = () => {

    const { xlg, sm, med } = useViewport()
    const [visible, setVisible] = useState(false);

    const variableData = [
        {
          variable: "subreddit",
          type: "Categorical (Nominal)",
          description:
            "The specific Reddit community where the comment was posted (e.g., r/funny, r/gaming, r/technology).",
          purpose:
            "Allows comparison of bot activity across different communities.",
        },
        {
          variable: "account_age_days",
          type: "Quantitative (Continuous)",
          description:
            "Age of the commenting account in days. Range: ~168 – 2996 days. Mean ≈ 1160 days.",
          purpose:
            "Useful for detecting newer “throwaway” bot accounts or long-standing accounts with abnormal activity patterns.",
        },
        {
          variable: "user_karma",
          type: "Quantitative (Continuous)",
          description:
            "Total accumulated karma score for the user. Range: 308 – ~49,700. Mean ≈ 25,200.",
          purpose:
            "Helps identify unusual engagement patterns such as karma farming or artificially boosted accounts.",
        },
        {
          variable: "reply_delay_seconds",
          type: "Quantitative (Continuous / Time)",
          description:
            "Time difference between the original post and the comment reply. Range: 1 – 3577 seconds. Mean ≈ 1030 seconds.",
          purpose:
            "Extremely fast responses may indicate automated posting behaviour.",
        },
        {
          variable: "sentiment_score",
          type: "Quantitative (Continuous)",
          description:
            "Sentiment value ranging from -1 (negative) to +1 (positive) representing the emotional tone of the comment.",
          purpose:
            "Bots may produce more neutral or patterned sentiment compared to human conversation.",
        },
        {
          variable: "avg_word_length",
          type: "Quantitative (Continuous)",
          description:
            "Average number of characters per word in the comment text. Range: 4.03 – 7.49 characters.",
          purpose:
            "Synthetic text often shows different linguistic structure than human writing.",
        },
        {
          variable: "contains_links",
          type: "Boolean",
          description:
            "Indicates whether the comment contains an external link (True / False).",
          purpose:
            "Spam bots frequently include external links for promotion or phishing.",
        },
        {
          variable: "is_bot_flag",
          type: "Boolean (Target Variable)",
          description:
            "Ground truth label indicating whether the comment was generated by a bot.",
          purpose:
            "Primary variable used to compare bot vs human behaviour.",
        },
        {
          variable: "bot_type_label",
          type: "Categorical (Nominal)",
          description:
            "Classification of bot subtype (e.g., Reprint Bot, AI Summarizer, Engagement Farmer, None for human).",
          purpose:
            "Enables deeper analysis of different kinds of automated accounts.",
        },
      ];
      

    // Animation clear out
    useEffect(() => {
        const t = setTimeout(() => setVisible(true), 100);
        return () => clearTimeout(t);
    }, []);


    return (
        <section>
            <main style={{
                flex: 1,
                paddingLeft: "3rem",
                paddingRight: "3rem",
                maxWidth: "100%",
                position: "relative",
                boxSizing: "border-box",
                height: "auto",
            }}>
                {/* Header */}
                <div style={{
                    opacity: visible ? 1 : 0.01,
                    transform: visible ? "translateY(0)" : "translateY(-16px)",
                    transition: "opacity 0.6s 0.1s, transform 0.6s 0.1s",
                }}>
                    <h1 style={{
                        textAlign: "left",
                        fontSize: "clamp(48px, 5vw, 68px)",
                        fontWeight: "800",
                        color: "#F0E2C8",
                        margin: "0 0 20px 0",
                        letterSpacing: "-0.5px",
                        lineHeight: 1,
                        fontFamily: "'Georgia', serif",
                    }}>
                        Category Breakdown
                    </h1>
                    <p style={{
                        textAlign: "left",
                        fontSize: "clamp(0.5rem, 6.5vw, 1rem)",
                        lineHeight: "1.75",
                        color: "#EAC46A",
                        maxWidth: xlg ? "60%" : "100%",
                        margin: "0 0 40px 0",
                        letterSpacing: "0.2px",
                    }}>
The dataset contains metadata about Reddit comments that may help distinguish automated accounts from human users. The variables include categorical, quantitative, and boolean data types that capture behavioural patterns, linguistic features, and engagement characteristics.                    </p>
                </div>
                <div>
                    <TableChart data={variableData} title={""} subtitle={""}/>
                </div>

            
            </main>
        </section>
    )
}